name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Updated to match dependency requirements
      - name: Lint frontend
        working-directory: frontend
        run: |
          npm install
          npm run lint || true
      - name: Lint backend
        working-directory: backend
        run: |
          npm install
          npx eslint . || true

  test-backend:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Clean Workspace
        run: rm -rf * && git reset --hard
      - name: Install & Run Backend Tests
        working-directory: backend
        run: |
          npm install
          npm test

  test-frontend:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Clean Workspace
        run: rm -rf * && git reset --hard
      - name: Install & Run Frontend Tests
        working-directory: frontend
        run: |
          npm install
          npm test -- --watchAll=false

  integration-test:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Clean Workspace
        run: rm -rf * && git reset --hard
      - name: Start Services
        run: |
          cd backend && npm install && node index.js &
          cd ../frontend && npm install && npm run build && npx serve -s build &
          sleep 10  # Wait for services to start
      - name: Run integration smoke-test
        run: ./scripts/integration.sh

  docker-build:
    runs-on: ubuntu-latest
    needs: [integration-test]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Docker image
        run: docker build . -t rajeevbarnwal/stock-tracker:ci
